title: Ersen ELMAOGULLARI Personal Web Site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/flexible-jekyll" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ersen ELMAOGULLARI
author-img: ersen-elmaogullari.jpg # add your photo
about-author:  A self-motivated Information Technologies enthusiast; more than 20 years of field and consultancy experience on enterprise level systems and storage management, backup, storage / server virtualization, leveraging open source and big data solutions to existing infrastructures, especially in telecommunications, finance, national security and government sectors. … 
social-twitter: elmaogullari
social-github: elmaogullari
social-linkedin: elmaogullari
social-email: elmaogullari@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
